services:
  frontend:
    image: your-angular-image
    container_name: todo-frontend
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /var/lib/jenkins/security-reports:/var/lib/jenkins/security-reports:ro

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3000:3000"
    restart: always
